### ISSUE TITLE
Multiple Instances of VST

### ISSUE THREAD

**Issue by deathybrs** [deathybrs/SIDStep2#11]
For some reason, most DAWs will not allow multiple instances of SIDStep2.  This is vital to targeting the Mega65, and the only DAW that can do it right now is Bitwig because it sandboxes the VSTs.  Figure out why it chokes in other DAWs.

**Comment by sagamusix** [comment]
Do you have any global state? Maybe in reSID itself? I can confirm in OpenMPT that unless I really force each plugin instance to run in its own process (via the plugin bridge, similar to Bitwig I assume), I can hear the notes from one instance being played through the other instance.

**Comment by deathybrs** [comment]
I am pretty sure that is the case, although I would have hoped that JUCE would have by default made it so VSTs could be multi-instanced.  That said, I have not updated the JUCE version for quite a long while, as I don't want to pay the cost of bringing it up to date until AFTER I have a 1.0 release, so it may have been fixed at a later date.

I will take a look in a debugger to see where it's choking, it's just a lower priority than getting vibrato and pitch bend working right now.

**Comment by sagamusix** [comment]
That should definitely be the default with JUCE - I have used tons of JUCE-based plugins, not a single one had this problem.

**Comment by deathybrs** [comment]
Yeah, that's what I would expect.  It's probably something silly, I probably did something dumb.

**Comment by deathybrs** [comment]
So, yeah... my biggest problem are that I use a singleton for my event system so that my message consumers and emitters don't have to observe each other to communicate later.

**Comment by deathybrs** [comment]
Whelp, there's that... the event system is now completely broken in my local codebase until I finish this refactoring.

**Comment by deathybrs** [comment]
As expected, the complete overhaul has left the whole thing so broken that the VST doesn't even pass the DAW's sniff test for whether it's a VST or not.

**Comment by deathybrs** [comment]
Right, that's that.  The event system has been completely refactored and it should now be possible to load multiple instances of the VST in any DAW.  At this time, I have only actually tested with Ableton and Bitwig (and, of course, I still need to release a build before most people can test it).
